% BASH.M solves six least square problems mentioned in //Testing
% Unconstrained Optimization Software//, namely Meyer function, namely
% Meyer Function, Osborne Exponential I Function, Osborne Exponential II
% Function, Jennrich & Sampson Funtion, Freudenstein and Roth Function and 
% Davidon Function function, with the inner function lsqnonlin().

% Date:     Jun 11th, 2018
% Creator:  BroC

x0s = {[.02, 4000, 250]', ...
       [.5, 1.5, -1, .01, .02]', ...
       [1.3, .65, .65, .7, .6, 3, 5, 7, 2, 4.5, 5.5]', ...
       [.3, .4]', ...
       [.5, -2]', ...
       [25, 5, -5, 1]'};

fs = {@r_meyer, ...
      @r_osborne1, ...
      @r_osborne2, ...
      @r_js, ...
      @r_fr, ...
      @r_davidon};

xs = cell(6,1);
rnorm = zeros(6,1);
res = xs;
flags = rnorm;

for i=1:6
    [ xs{i},rnorm(i),res{i},flags(i) ] = lsqnonlin(fs{i},x0s{i});
end